11:11:04.368 [INFO ] i.g.c.c.GatlingConfiguration$ - Gatling will try to use 'gatling.conf' as custom config file.
11:11:05.135 [INFO ] a.e.s.Slf4jLogger - Slf4jLogger started
11:11:06.650 [INFO ] i.g.h.e.HttpEngine - Start warm up
11:11:07.770 [INFO ] i.g.h.e.HttpEngine - Couldn't execute warm up request https://gatling.io: i.g.h.c.i.RequestTimeoutException: Request timeout after 1000 ms
11:11:07.774 [INFO ] i.g.h.e.HttpEngine - Warm up done
11:11:08.882 [INFO ] i.g.c.s.w.ConsoleDataWriter - Initializing
11:11:08.888 [INFO ] i.g.c.s.w.LogFileDataWriter - Initializing
11:11:08.897 [INFO ] i.g.c.s.w.ConsoleDataWriter - Initialized
11:11:08.904 [INFO ] i.g.c.s.w.LogFileDataWriter - Initialized
11:11:08.968 [INFO ] i.g.c.c.i.Injector - StoppedInjecting
11:11:10.036 [INFO ] i.g.h.e.r.DefaultStatsProcessor - Request 'Pedido' failed for user 2: status.find.is(200), but actually found 500
11:11:10.044 [DEBUG] i.g.h.e.r.DefaultStatsProcessor - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
Pedido: KO status.find.is(200), but actually found 500
=========================
Session:
Session(Pedido,2,1582733468934,Map(ItemCode1 -> 0500000150, Address2 -> F97B037 MARIA SOL TOUMA, gatling.http.cache.baseUrl -> http://ws.resgasa.com.ec:89, CostingCode1 -> 100, U_RSG_RUTA2 -> 97, CostingCode4 -> 100, gatling.http.cache.dns -> io.gatling.http.cache.DnsCacheSupport$$anon$1@3de6f407, Quantity5 -> 10, Comments -> ResTest26a55558313, tokenType -> bearer, U_RSG_TIPOVTA -> 1, U_RSG_RUTA1 -> 97, Address3 -> F97B037 MARIA SOL TOUMA, Address5 -> F97B037 MARIA SOL TOUMA, CostingCode2 -> 100, ItemCode4 -> 0500000762, Address4 -> F97B037 MARIA SOL TOUMA, CostingCode3 -> 100, U_RSG_CODVEN_EXT -> 1028, Quantity4 -> 3, U_RSG_RUTA4 -> 97, nuevo_pedido_test -> {"error":{"code":"","message":"An error has occurred.","innererror":{"message":"Error guardando en el log","type":"System.Exception","stacktrace":"   at DistribucionYLiquidacion.Framework.Utililes.UtilFile.EscribirEnArchivoDesdeAddon(String mensaje)\r\n   at WebApi.Controllers.PedidoController.<PostAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at WebApi.Controllers.PedidoController.<Post>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"}}}, TaxDate -> 2020-02-26, Quantity1 -> 10, ItemCode3 -> 0500000758, gatling.http.ssl.sslContexts -> SslContexts(io.netty.handler.ssl.ReferenceCountedOpenSslClientContext@4ab6e90c,None), U_RSG_RUTA3 -> 97, CardCode -> 59864, tokenId -> kERBRfsSdCrF0bqx9vi1rWRM0YJ6masIK9ULbi2o8oCMVb5dJq6MI4lV48b3UZnn3-nYOCdhkyDHUKFIgnbOTNV4BwWYrrOT8HAdwE3s-yjun3GvAX2ZXlhBKh3nc-E-owzGSFVOvJlbxYeEMdWaeN2fnOlwzv8iXmQrScgRRWq_6FDljYbmfy7D3eui8CR8q8FNrPXOT9H4mnDEKa9L__nCjAnMQeil6VSsS1ucOiyDqM7dXTIxy0WEXRVD6kGZEslQNhrGvOYbveb6d3FdO0meUoBnB2nLVvi5QSEX0DM1iSPveJoySCMY4gOi5c8QmieaXgikJsEfyr_v7uoxNA, U_RSG_RUTA5 -> 97, DocDueDate -> 2020-02-26, Quantity3 -> 2, Address1 -> F97B037 MARIA SOL TOUMA, ItemCode5 -> 0500000765, 11815dbe-676a-409b-8886-696b731e6984 -> 0, DocDate -> 2020-02-26, ImportFileNum -> 1946, NumAtCard -> 6697, CostingCode5 -> 100, ItemCode2 -> 0500000757, Quantity2 -> 12),200,KO,List(ExitOnCompleteLoopBlock(11815dbe-676a-409b-8886-696b731e6984)),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$500/818785904@5d30031f)
=========================
HTTP request:
POST http://ws.resgasa.com.ec:89/odata/Pedido
headers=
Authorization: bearer kERBRfsSdCrF0bqx9vi1rWRM0YJ6masIK9ULbi2o8oCMVb5dJq6MI4lV48b3UZnn3-nYOCdhkyDHUKFIgnbOTNV4BwWYrrOT8HAdwE3s-yjun3GvAX2ZXlhBKh3nc-E-owzGSFVOvJlbxYeEMdWaeN2fnOlwzv8iXmQrScgRRWq_6FDljYbmfy7D3eui8CR8q8FNrPXOT9H4mnDEKa9L__nCjAnMQeil6VSsS1ucOiyDqM7dXTIxy0WEXRVD6kGZEslQNhrGvOYbveb6d3FdO0meUoBnB2nLVvi5QSEX0DM1iSPveJoySCMY4gOi5c8QmieaXgikJsEfyr_v7uoxNA
Accept: application/json
host: ws.resgasa.com.ec:89
content-type: application/json
content-length: 1366
byteArraysBody={
    "CardCode": "59864",
    "DocDate": "2020-02-26",
    "DocDueDate": "2020-02-26",
    "TaxDate": "2020-02-26",
    "U_RSG_TIPOVTA": "1",
    "U_RSG_CODVEN_EXT": "1028",
    "Comments": "ResTest26a55558313",
    "NumAtCard": "6697",
    "ImportFileNum": "1946",
    "DocumentLines": [
        {
            "ItemCode": "0500000150",
            "Quantity": "10",
            "CostingCode" : "100",
            "U_RSG_RUTA": "97",
            "Address": "F97B037 MARIA SOL TOUMA"
        },
        {
            "ItemCode": "0500000757",
            "Quantity": "12",
            "CostingCode" : "100",
            "U_RSG_RUTA": "97",
            "Address": "F97B037 MARIA SOL TOUMA"
        },
        {
            "ItemCode": "0500000758",
            "Quantity": "2",
            "CostingCode" : "100",
            "U_RSG_RUTA": "97",
            "Address": "F97B037 MARIA SOL TOUMA"
        },
        {
            "ItemCode": "0500000762",
            "Quantity": "3",
            "CostingCode" : "100",
            "U_RSG_RUTA": "97",
            "Address": "F97B037 MARIA SOL TOUMA"
        },
        {
            "ItemCode": "0500000765",
            "Quantity": "10",
            "CostingCode" : "100",
            "U_RSG_RUTA": "97",
            "Address": "F97B037 MARIA SOL TOUMA"
        }
    ]
}
=========================
HTTP response:
status=
500 Internal Server Error
headers= 
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; odata.metadata=minimal
Expires: -1
Server: Microsoft-IIS/8.5
OData-Version: 4.0
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Wed, 26 Feb 2020 16:11:09 GMT
Content-Length: 2740

body=
{"error":{"code":"","message":"An error has occurred.","innererror":{"message":"Error guardando en el log","type":"System.Exception","stacktrace":"   at DistribucionYLiquidacion.Framework.Utililes.UtilFile.EscribirEnArchivoDesdeAddon(String mensaje)\r\n   at WebApi.Controllers.PedidoController.<PostAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at WebApi.Controllers.PedidoController.<Post>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"}}}
<<<<<<<<<<<<<<<<<<<<<<<<<
11:11:10.036 [INFO ] i.g.h.e.r.DefaultStatsProcessor - Request 'Pedido' failed for user 39: status.find.is(200), but actually found 500
11:11:10.046 [DEBUG] i.g.h.e.r.DefaultStatsProcessor - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
Pedido: KO status.find.is(200), but actually found 500
=========================
Session:
Session(Pedido,39,1582733469052,Map(ItemCode1 -> 0500000768, Address2 -> 53991C016 PRIMAX PERIMETRAL, gatling.http.cache.baseUrl -> http://ws.resgasa.com.ec:89, CostingCode1 -> 100, U_RSG_RUTA2 -> 89, CostingCode4 -> 100, gatling.http.cache.dns -> io.gatling.http.cache.DnsCacheSupport$$anon$1@3de6f407, Quantity5 -> 10, Comments -> ResTest26a55557902, tokenType -> bearer, U_RSG_TIPOVTA -> 1, U_RSG_RUTA1 -> 89, Address3 -> 53991C016 PRIMAX PERIMETRAL, Address5 -> 53991C016 PRIMAX PERIMETRAL, CostingCode2 -> 100, ItemCode4 -> 0500000128, Address4 -> 53991C016 PRIMAX PERIMETRAL, CostingCode3 -> 100, U_RSG_CODVEN_EXT -> 1028, Quantity4 -> 3, U_RSG_RUTA4 -> 89, nuevo_pedido_test -> {"error":{"code":"","message":"An error has occurred.","innererror":{"message":"Error guardando en el log","type":"System.Exception","stacktrace":"   at DistribucionYLiquidacion.Framework.Utililes.UtilFile.EscribirEnArchivoDesdeAddon(String mensaje)\r\n   at WebApi.Controllers.PedidoController.<PostAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at WebApi.Controllers.PedidoController.<Post>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"}}}, TaxDate -> 2020-02-26, Quantity1 -> 10, ItemCode3 -> 0500000119, gatling.http.ssl.sslContexts -> SslContexts(io.netty.handler.ssl.ReferenceCountedOpenSslClientContext@5b887605,None), U_RSG_RUTA3 -> 89, CardCode -> 53991, tokenId -> DTCfX0CkccSfKpfyhkr7HwW1f3f1VWUqjsq6ZYYdnhNhr14pdo930sI-iJMBDfEyzaONdtwBjMRqRat3c1SriO5Z_gtLnAFPs51ocTmJ3yFplduJcmN9fbajlBGWXsHu9-9HtoJKT-QL24hZhPFSkak4GMLK_WTxFhstgfjdwC8LbH_llhsaYhqrQCfHStR3WqbUBJfHZKYyj-oHpKiRupphRk2KM7YRAbRVAg7bRkgEK4Yt3CWl7fvzfqGCVzTMVVdAKgoG7n9EbsGyMSuyXoaamFp9nAo8X6Gp6l4jhnw0L-BDs90Qikqm0lw4NAbZF1w1xgdzyHdY5EIGAQ0A-w, U_RSG_RUTA5 -> 89, DocDueDate -> 2020-02-26, Quantity3 -> 2, Address1 -> 53991C016 PRIMAX PERIMETRAL, ItemCode5 -> 0500000133, 11815dbe-676a-409b-8886-696b731e6984 -> 0, DocDate -> 2020-02-26, ImportFileNum -> 1946, NumAtCard -> 6697, CostingCode5 -> 100, ItemCode2 -> 0500000118, Quantity2 -> 12),190,KO,List(ExitOnCompleteLoopBlock(11815dbe-676a-409b-8886-696b731e6984)),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$500/818785904@5d30031f)
=========================
HTTP request:
POST http://ws.resgasa.com.ec:89/odata/Pedido
headers=
Authorization: bearer DTCfX0CkccSfKpfyhkr7HwW1f3f1VWUqjsq6ZYYdnhNhr14pdo930sI-iJMBDfEyzaONdtwBjMRqRat3c1SriO5Z_gtLnAFPs51ocTmJ3yFplduJcmN9fbajlBGWXsHu9-9HtoJKT-QL24hZhPFSkak4GMLK_WTxFhstgfjdwC8LbH_llhsaYhqrQCfHStR3WqbUBJfHZKYyj-oHpKiRupphRk2KM7YRAbRVAg7bRkgEK4Yt3CWl7fvzfqGCVzTMVVdAKgoG7n9EbsGyMSuyXoaamFp9nAo8X6Gp6l4jhnw0L-BDs90Qikqm0lw4NAbZF1w1xgdzyHdY5EIGAQ0A-w
Accept: application/json
host: ws.resgasa.com.ec:89
content-type: application/json
content-length: 1386
byteArraysBody={
    "CardCode": "53991",
    "DocDate": "2020-02-26",
    "DocDueDate": "2020-02-26",
    "TaxDate": "2020-02-26",
    "U_RSG_TIPOVTA": "1",
    "U_RSG_CODVEN_EXT": "1028",
    "Comments": "ResTest26a55557902",
    "NumAtCard": "6697",
    "ImportFileNum": "1946",
    "DocumentLines": [
        {
            "ItemCode": "0500000768",
            "Quantity": "10",
            "CostingCode" : "100",
            "U_RSG_RUTA": "89",
            "Address": "53991C016 PRIMAX PERIMETRAL"
        },
        {
            "ItemCode": "0500000118",
            "Quantity": "12",
            "CostingCode" : "100",
            "U_RSG_RUTA": "89",
            "Address": "53991C016 PRIMAX PERIMETRAL"
        },
        {
            "ItemCode": "0500000119",
            "Quantity": "2",
            "CostingCode" : "100",
            "U_RSG_RUTA": "89",
            "Address": "53991C016 PRIMAX PERIMETRAL"
        },
        {
            "ItemCode": "0500000128",
            "Quantity": "3",
            "CostingCode" : "100",
            "U_RSG_RUTA": "89",
            "Address": "53991C016 PRIMAX PERIMETRAL"
        },
        {
            "ItemCode": "0500000133",
            "Quantity": "10",
            "CostingCode" : "100",
            "U_RSG_RUTA": "89",
            "Address": "53991C016 PRIMAX PERIMETRAL"
        }
    ]
}
=========================
HTTP response:
status=
500 Internal Server Error
headers= 
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; odata.metadata=minimal
Expires: -1
Server: Microsoft-IIS/8.5
OData-Version: 4.0
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Wed, 26 Feb 2020 16:11:09 GMT
Content-Length: 2740

body=
{"error":{"code":"","message":"An error has occurred.","innererror":{"message":"Error guardando en el log","type":"System.Exception","stacktrace":"   at DistribucionYLiquidacion.Framework.Utililes.UtilFile.EscribirEnArchivoDesdeAddon(String mensaje)\r\n   at WebApi.Controllers.PedidoController.<PostAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at WebApi.Controllers.PedidoController.<Post>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"}}}
<<<<<<<<<<<<<<<<<<<<<<<<<
